### ISSUE TITLE
doesnt work for me

### ISSUE THREAD

**Issue by kubsakkk** [SeiyaGame/Discord-ShowHiddenChannels#1]
i tried changing the name of the plugin and still doesnt work
if its working for u please do a step-by-step

**Comment by Hountez** [comment]
sadly it is not enough to just restore the file with the change, there are changes in the library too:
![image](https://user-images.githubusercontent.com/18191359/188483918-dc849073-348e-40be-bfc6-30b688570f6a.png)

these entries are missing in the 0BDFDB.data.json file, when you restore these entries and replace ShowHiddenChannels with ShowHiddenChannels_OLDEST it works again (do not touch the variables with _ only the ones that are named exactly ShowHiddenChannels)

also, you need to revert this change:
![image](https://user-images.githubusercontent.com/18191359/188485009-1ac14a35-14e9-44c4-8095-b86fb71ece0e.png)

BUT: since this is used by other plugins this could crash them if they use this variable

**Comment by kubsakkk** [comment]
so like this?
![image](https://user-images.githubusercontent.com/74510831/188487211-fecdaf94-3078-42a7-81c7-d04cf5829d5c.png)

![image](https://user-images.githubusercontent.com/74510831/188487189-7fbc07a4-a71b-4fda-b950-6005c1dc7374.png)

**Comment by kubsakkk** [comment]
and like this? 
![image](https://user-images.githubusercontent.com/74510831/188487257-55727dde-454f-4b2f-9fd9-1b64e6a7b389.png)

**Comment by kubsakkk** [comment]
if that's correct i got an error upon opening bd 
![image](https://user-images.githubusercontent.com/74510831/188487376-0bb55c90-a62d-46ab-a970-1e812ccb6989.png)

**Comment by Hountez** [comment]
I just realized I used an old version of the library, the new one has more changes, this error pops up if the hash values of the files are not the same as on his GitHub, so changes are locked now, you could probably remove the check but as I said this is a library other plugins are built on, so it would crash other plugins in the future.

**Comment by SeiyaGame** [comment]
Hi, can you try again now ! I have updated
It's working on my side :blush:
**Please read the README file**

**Comment by s11s1s1** [comment]
hi, it doesn't work

**Comment by BlackStalker503** [comment]
Agree with @s11s1s1
It doesn't work even if do as it is written in README.
Also after reinstall plugin, in "plugins" script and config have different names

**Comment by SeiyaGame** [comment]
Hi, sorry for the delay, normally the changes made should work! Follow the README again. Tell me again if it doesn't work

**Comment by s11s1s1** [comment]
now it works

**Comment by SeiyaGame** [comment]
Tell me, if the problem comes up again :blush:
I close this issue
